
A `Promise` that was callbackified via `util.callbackify()` was rejected with a
falsy value.

<a id="ERR_HTTP_HEADERS_SENT"></a>